import { Page, Text, View } from '@react-pdf/renderer'
import { styles } from './pdfStyles'

interface PDFTitlePageProps {
  themeCount: number
  clusterCount: number
  entityCount: number
  exportDate: string
}

export default function PDFTitlePage({ themeCount, clusterCount, entityCount, exportDate }: PDFTitlePageProps) {
  return (
    <Page size="A4" style={styles.page}>
      <View style={styles.titlePage}>
        <Text style={styles.mainTitle}>Research Synthesis Report</Text>
        <Text style={styles.subtitle}>Strategic insights from user research</Text>
        <Text style={styles.titleDate}>Exported on {exportDate}</Text>

        <View style={{ marginTop: 40, marginBottom: 40 }}>
          <Text style={styles.titleStats}>
            {themeCount} {themeCount === 1 ? 'Theme' : 'Themes'} • {clusterCount} {clusterCount === 1 ? 'Cluster' : 'Clusters'} • {entityCount} {entityCount === 1 ? 'Entity' : 'Entities'}
          </Text>
        </View>

        <Text style={styles.titleFooter}>Generated by Research Synthesis Dashboard</Text>
      </View>
    </Page>
  )
}
